"""The closed set of reason codes.

Every verdict and every refusal returned to an agent carries one of these. Adding a refusal path
means adding a member here, never returning a bare error. Each code also declares what the agent
should do next, so responses are machine-actionable without parsing prose.
"""

from __future__ import annotations

from enum import StrEnum


class AgentAction(StrEnum):
    """What an agent can usefully do in response to a refusal."""

    PROCEED = "proceed"
    RETRY = "retry"
    PRESENT_CREDENTIALS = "present_credentials"
    REDUCE_CART = "reduce_cart"
    WAIT = "wait"
    STOP = "stop"


class Decision(StrEnum):
    ALLOW = "allow"
    DENY = "deny"
    ESCALATE = "escalate"
    CHALLENGE = "challenge"


class ReasonCode(StrEnum):
    # Approvals
    APPROVED = "APPROVED"
    APPROVED_WITHIN_UNVERIFIED_CEILING = "APPROVED_WITHIN_UNVERIFIED_CEILING"
    APPROVED_AFTER_HUMAN_APPROVAL = "APPROVED_AFTER_HUMAN_APPROVAL"

    # Step 1: well-formedness and signature
    CRED_MALFORMED = "CRED_MALFORMED"
    CRED_SIGNATURE_INVALID = "CRED_SIGNATURE_INVALID"
    CRED_SCHEMA_INVALID = "CRED_SCHEMA_INVALID"

    # Step 2: subject binding
    CRED_SUBJECT_MISMATCH = "CRED_SUBJECT_MISMATCH"
    CRED_KEY_BINDING_MISSING = "CRED_KEY_BINDING_MISSING"
    CRED_KEY_BINDING_INVALID = "CRED_KEY_BINDING_INVALID"

    # Step 3: issuer trust
    CRED_ISSUER_UNKNOWN = "CRED_ISSUER_UNKNOWN"
    CRED_ISSUER_TIER_INSUFFICIENT = "CRED_ISSUER_TIER_INSUFFICIENT"

    # Step 4: validity window
    CRED_EXPIRED = "CRED_EXPIRED"
    CRED_NOT_YET_VALID = "CRED_NOT_YET_VALID"

    # Step 5: replay
    CRED_REPLAYED = "CRED_REPLAYED"

    # Step 6: binding to the merchant's signed Checkout
    CHECKOUT_BINDING_MISMATCH = "CHECKOUT_BINDING_MISMATCH"
    CHECKOUT_UNKNOWN = "CHECKOUT_UNKNOWN"
    CHECKOUT_EXPIRED = "CHECKOUT_EXPIRED"
    CART_ALTERED_AFTER_SIGNING = "CART_ALTERED_AFTER_SIGNING"
    CHECKOUT_ALREADY_SETTLED = "CHECKOUT_ALREADY_SETTLED"
    PRICE_DRIFT = "PRICE_DRIFT"
    POLICY_HASH_MISMATCH = "POLICY_HASH_MISMATCH"

    # Step 7: closed satisfies open
    CONSTRAINT_MERCHANT_NOT_ALLOWED = "CONSTRAINT_MERCHANT_NOT_ALLOWED"
    CONSTRAINT_LINE_ITEM_UNSATISFIED = "CONSTRAINT_LINE_ITEM_UNSATISFIED"
    CONSTRAINT_AMOUNT_EXCEEDED = "CONSTRAINT_AMOUNT_EXCEEDED"
    CONSTRAINT_AMOUNT_BELOW_MINIMUM = "CONSTRAINT_AMOUNT_BELOW_MINIMUM"
    CONSTRAINT_CURRENCY_MISMATCH = "CONSTRAINT_CURRENCY_MISMATCH"
    CONSTRAINT_PAYEE_NOT_ALLOWED = "CONSTRAINT_PAYEE_NOT_ALLOWED"
    CONSTRAINT_INSTRUMENT_NOT_ALLOWED = "CONSTRAINT_INSTRUMENT_NOT_ALLOWED"
    CONSTRAINT_PISP_NOT_ALLOWED = "CONSTRAINT_PISP_NOT_ALLOWED"
    CONSTRAINT_EXECUTION_WINDOW = "CONSTRAINT_EXECUTION_WINDOW"
    CONSTRAINT_RECURRENCE_EXHAUSTED = "CONSTRAINT_RECURRENCE_EXHAUSTED"
    CONSTRAINT_PAYMENT_REFERENCE_MISMATCH = "CONSTRAINT_PAYMENT_REFERENCE_MISMATCH"
    CONSTRAINT_BUDGET_EXCEEDED = "CONSTRAINT_BUDGET_EXCEEDED"
    CONSTRAINT_UNRESOLVED = "CONSTRAINT_UNRESOLVED"

    # Step 8: presence, when a human-present checkout claims one
    PRESENCE_ATTESTATION_INVALID = "PRESENCE_ATTESTATION_INVALID"
    PRESENCE_ATTESTATION_STALE = "PRESENCE_ATTESTATION_STALE"
    PRESENCE_BINDING_MISMATCH = "PRESENCE_BINDING_MISMATCH"
    PRESENCE_ISSUER_UNTRUSTED = "PRESENCE_ISSUER_UNTRUSTED"
    PRESENCE_REPLAYED = "PRESENCE_REPLAYED"

    # Semantic path
    SEMANTIC_DENIED = "SEMANTIC_DENIED"
    ESCALATION_REQUIRED = "ESCALATION_REQUIRED"
    ESCALATION_DENIED = "ESCALATION_DENIED"
    ESCALATION_TIMEOUT = "ESCALATION_TIMEOUT"
    ESCALATION_CART_CHANGED = "ESCALATION_CART_CHANGED"

    # Budget, velocity and structuring
    BUDGET_EXCEEDED = "BUDGET_EXCEEDED"
    BUDGET_RESERVATION_FAILED = "BUDGET_RESERVATION_FAILED"
    VELOCITY_SPEND_EXCEEDED = "VELOCITY_SPEND_EXCEEDED"
    VELOCITY_COUNT_EXCEEDED = "VELOCITY_COUNT_EXCEEDED"
    STRUCTURING_DETECTED = "STRUCTURING_DETECTED"

    # Catalog and item policy
    CATEGORY_FORBIDDEN = "CATEGORY_FORBIDDEN"
    ITEM_AGE_RESTRICTED = "ITEM_AGE_RESTRICTED"
    ITEM_REGION_LOCKED = "ITEM_REGION_LOCKED"
    QUANTITY_OUT_OF_RANGE = "QUANTITY_OUT_OF_RANGE"
    ITEM_UNKNOWN = "ITEM_UNKNOWN"

    # Inventory
    INVENTORY_UNAVAILABLE = "INVENTORY_UNAVAILABLE"
    HOLD_QUOTA_EXCEEDED = "HOLD_QUOTA_EXCEEDED"
    HOLD_EXPIRED = "HOLD_EXPIRED"

    # Agent and mandate state
    AGENT_KILL_SWITCH = "AGENT_KILL_SWITCH"
    MANDATE_REVOKED = "MANDATE_REVOKED"
    MANDATE_UNKNOWN = "MANDATE_UNKNOWN"

    # Degraded path for unverifiable agents
    UNVERIFIED_CEILING_EXCEEDED = "UNVERIFIED_CEILING_EXCEEDED"
    UNVERIFIED_CATEGORY_FORBIDDEN = "UNVERIFIED_CATEGORY_FORBIDDEN"

    # Payment execution
    PAYMENT_VERDICT_MISSING = "PAYMENT_VERDICT_MISSING"
    PAYMENT_GATEWAY_ERROR = "PAYMENT_GATEWAY_ERROR"
    PAYMENT_RECONCILIATION_DISCREPANCY = "PAYMENT_RECONCILIATION_DISCREPANCY"
    WEBHOOK_SIGNATURE_INVALID = "WEBHOOK_SIGNATURE_INVALID"

    # Compensation
    REVOKED_AFTER_CAPTURE_COMPENSATED = "REVOKED_AFTER_CAPTURE_COMPENSATED"


APPROVAL_CODES: frozenset[ReasonCode] = frozenset(
    {
        ReasonCode.APPROVED,
        ReasonCode.APPROVED_WITHIN_UNVERIFIED_CEILING,
        ReasonCode.APPROVED_AFTER_HUMAN_APPROVAL,
    }
)


ACTIONS: dict[ReasonCode, AgentAction] = {
    ReasonCode.APPROVED: AgentAction.PROCEED,
    ReasonCode.APPROVED_WITHIN_UNVERIFIED_CEILING: AgentAction.PROCEED,
    ReasonCode.APPROVED_AFTER_HUMAN_APPROVAL: AgentAction.PROCEED,
    ReasonCode.CRED_MALFORMED: AgentAction.PRESENT_CREDENTIALS,
    ReasonCode.CRED_SIGNATURE_INVALID: AgentAction.PRESENT_CREDENTIALS,
    ReasonCode.CRED_SCHEMA_INVALID: AgentAction.PRESENT_CREDENTIALS,
    ReasonCode.CRED_SUBJECT_MISMATCH: AgentAction.PRESENT_CREDENTIALS,
    ReasonCode.CRED_KEY_BINDING_MISSING: AgentAction.PRESENT_CREDENTIALS,
    ReasonCode.CRED_KEY_BINDING_INVALID: AgentAction.PRESENT_CREDENTIALS,
    ReasonCode.CRED_ISSUER_UNKNOWN: AgentAction.PRESENT_CREDENTIALS,
    ReasonCode.CRED_ISSUER_TIER_INSUFFICIENT: AgentAction.PRESENT_CREDENTIALS,
    ReasonCode.CRED_EXPIRED: AgentAction.PRESENT_CREDENTIALS,
    ReasonCode.CRED_NOT_YET_VALID: AgentAction.WAIT,
    ReasonCode.CRED_REPLAYED: AgentAction.PRESENT_CREDENTIALS,
    ReasonCode.CHECKOUT_BINDING_MISMATCH: AgentAction.RETRY,
    ReasonCode.CHECKOUT_UNKNOWN: AgentAction.RETRY,
    ReasonCode.CHECKOUT_EXPIRED: AgentAction.RETRY,
    ReasonCode.CHECKOUT_ALREADY_SETTLED: AgentAction.STOP,
    ReasonCode.CART_ALTERED_AFTER_SIGNING: AgentAction.RETRY,
    ReasonCode.PRICE_DRIFT: AgentAction.RETRY,
    ReasonCode.POLICY_HASH_MISMATCH: AgentAction.RETRY,
    ReasonCode.CONSTRAINT_MERCHANT_NOT_ALLOWED: AgentAction.STOP,
    ReasonCode.CONSTRAINT_LINE_ITEM_UNSATISFIED: AgentAction.REDUCE_CART,
    ReasonCode.CONSTRAINT_AMOUNT_EXCEEDED: AgentAction.REDUCE_CART,
    ReasonCode.CONSTRAINT_AMOUNT_BELOW_MINIMUM: AgentAction.STOP,
    ReasonCode.CONSTRAINT_CURRENCY_MISMATCH: AgentAction.STOP,
    ReasonCode.CONSTRAINT_PAYEE_NOT_ALLOWED: AgentAction.STOP,
    ReasonCode.CONSTRAINT_INSTRUMENT_NOT_ALLOWED: AgentAction.PRESENT_CREDENTIALS,
    ReasonCode.CONSTRAINT_PISP_NOT_ALLOWED: AgentAction.PRESENT_CREDENTIALS,
    ReasonCode.CONSTRAINT_EXECUTION_WINDOW: AgentAction.WAIT,
    ReasonCode.CONSTRAINT_RECURRENCE_EXHAUSTED: AgentAction.STOP,
    ReasonCode.CONSTRAINT_PAYMENT_REFERENCE_MISMATCH: AgentAction.RETRY,
    ReasonCode.CONSTRAINT_BUDGET_EXCEEDED: AgentAction.REDUCE_CART,
    ReasonCode.CONSTRAINT_UNRESOLVED: AgentAction.WAIT,
    ReasonCode.PRESENCE_ATTESTATION_INVALID: AgentAction.PRESENT_CREDENTIALS,
    ReasonCode.PRESENCE_ATTESTATION_STALE: AgentAction.PRESENT_CREDENTIALS,
    ReasonCode.PRESENCE_BINDING_MISMATCH: AgentAction.PRESENT_CREDENTIALS,
    ReasonCode.PRESENCE_ISSUER_UNTRUSTED: AgentAction.PRESENT_CREDENTIALS,
    ReasonCode.PRESENCE_REPLAYED: AgentAction.PRESENT_CREDENTIALS,
    ReasonCode.SEMANTIC_DENIED: AgentAction.REDUCE_CART,
    ReasonCode.ESCALATION_REQUIRED: AgentAction.WAIT,
    ReasonCode.ESCALATION_DENIED: AgentAction.STOP,
    ReasonCode.ESCALATION_TIMEOUT: AgentAction.STOP,
    ReasonCode.ESCALATION_CART_CHANGED: AgentAction.RETRY,
    ReasonCode.BUDGET_EXCEEDED: AgentAction.REDUCE_CART,
    ReasonCode.BUDGET_RESERVATION_FAILED: AgentAction.RETRY,
    ReasonCode.VELOCITY_SPEND_EXCEEDED: AgentAction.WAIT,
    ReasonCode.VELOCITY_COUNT_EXCEEDED: AgentAction.WAIT,
    ReasonCode.STRUCTURING_DETECTED: AgentAction.STOP,
    ReasonCode.CATEGORY_FORBIDDEN: AgentAction.REDUCE_CART,
    ReasonCode.ITEM_AGE_RESTRICTED: AgentAction.REDUCE_CART,
    ReasonCode.ITEM_REGION_LOCKED: AgentAction.REDUCE_CART,
    ReasonCode.QUANTITY_OUT_OF_RANGE: AgentAction.REDUCE_CART,
    ReasonCode.ITEM_UNKNOWN: AgentAction.REDUCE_CART,
    ReasonCode.INVENTORY_UNAVAILABLE: AgentAction.REDUCE_CART,
    ReasonCode.HOLD_QUOTA_EXCEEDED: AgentAction.WAIT,
    ReasonCode.HOLD_EXPIRED: AgentAction.RETRY,
    ReasonCode.AGENT_KILL_SWITCH: AgentAction.STOP,
    ReasonCode.MANDATE_REVOKED: AgentAction.STOP,
    ReasonCode.MANDATE_UNKNOWN: AgentAction.PRESENT_CREDENTIALS,
    ReasonCode.UNVERIFIED_CEILING_EXCEEDED: AgentAction.PRESENT_CREDENTIALS,
    ReasonCode.UNVERIFIED_CATEGORY_FORBIDDEN: AgentAction.PRESENT_CREDENTIALS,
    ReasonCode.PAYMENT_VERDICT_MISSING: AgentAction.STOP,
    ReasonCode.PAYMENT_GATEWAY_ERROR: AgentAction.RETRY,
    ReasonCode.PAYMENT_RECONCILIATION_DISCREPANCY: AgentAction.STOP,
    ReasonCode.WEBHOOK_SIGNATURE_INVALID: AgentAction.STOP,
    ReasonCode.REVOKED_AFTER_CAPTURE_COMPENSATED: AgentAction.STOP,
}

_RETRYABLE: frozenset[AgentAction] = frozenset({AgentAction.RETRY, AgentAction.WAIT})


def action_for(code: ReasonCode) -> AgentAction:
    return ACTIONS[code]


def is_retryable(code: ReasonCode) -> bool:
    return action_for(code) in _RETRYABLE


def is_approval(code: ReasonCode) -> bool:
    return code in APPROVAL_CODES
